#!/usr/bin/env bash
# traductor de linea de comandos
set -e
TRADUCCIONES=~/pdfs/traducciones
DESTINO=$TRADUCCIONES/$1_es.txt
THISFUNCTION=$$

  # estilos para prompt
  showmessage(){ echo -e "  \e[1;34;40m${@}\e[m" ;}
  showerror(){ echo -e "  \e[1;31;40m${@}\e[m" ;}

# verifica que la entrada sea un archivo de texto
if [ `file "$1" | grep -c 'text'` -ne 0 ]; then
	ENTRADA="$1"
else
	showerror ' !! entrada no valida, se esperaba un archivo de texto !!' && exit
fi

  animation() {
    tput civis
    chars="bpdqbpdq"
    while :; do
      local logprogress=$(tail -1 $DESTINO | sed 's/(\"|"|\n)+//g' )
      for (( i=1; i<${#chars}; i++ )); do
        sleep 0.05
        echo -en "\t  traduciendo [\e[3${i::1}m${chars:$i:1}\e[0m] | ${logprogress::39}  \e[m\r"
      done
    done
  }

  traductor() {
    local entry=$1
    local flaganimation
    animation & > $flaganimation
    function principal(){ echo "$(strings $entry)" | trans -u "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0" -no-browser -b :es ;}
    ( principal ) 2>/dev/null 1>$DESTINO

    tput civis
    kill $flaganimation
    exit
  }

  trap ctrl_c INT
  function ctrl_c(){ showerror "[*]Saliendo...\e[m\n" && tput cnorm && exit 0 ;}
  function initflag(){ traductor "$ENTRADA" ;}

# main
showmessage '['"$1"'] ====================> ['"$TRADUCCIONES"']' && initflag
kill $THISFUNCTION